---

- name: get composer.
  shell: curl -sS https://getcomposer.org/installer | php

- name: check composer.phar exists.
  stat:
    path: ~/composer.phar
  register: composer_phar_exists

- name: set composer.
  shell: mv composer.phar /usr/local/bin/composer
  when: composer_phar_exists.stat.exists == True
